# Generated by Django 6.0.1 on 2026-04-24 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fiber_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('sugar_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'db_table': 'foods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_weight', models.DecimalField(decimal_places=2, help_text='Target weight in lbs', max_digits=5)),
                ('daily_calories', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField(help_text='Protein in grams')),
                ('carbs', models.PositiveIntegerField(help_text='Carbs in grams')),
                ('fat', models.PositiveIntegerField(help_text='Fat in grams')),
                ('goal_type', models.CharField(choices=[('lose', 'Lose Weight'), ('gain', 'Gain Weight'), ('maintain', 'Maintain Weight')], max_length=10)),
                ('start_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='health.user')),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['-start_date'],
            },
        ),
    ]
