# Generated by Django 6.0.1 on 2026-04-24 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_food_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('lose', 'Lose Weight'), ('gain', 'Gain Weight'), ('maintain', 'Maintain Weight'), ('muscle gain', 'Muscle Gain')], max_length=15),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the meal', max_length=200)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('date', models.DateField(help_text='Date of the meal')),
                ('time', models.TimeField(help_text='Time of the meal')),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_carbs', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_fat', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='health.user')),
            ],
            options={
                'db_table': 'meals',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('meal_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_grams', models.DecimalField(decimal_places=2, help_text='Amount in grams', max_digits=7)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='health.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='health.meal')),
            ],
            options={
                'db_table': 'meal_items',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of the progress entry')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in lbs', max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Body fat percentage', max_digits=5, null=True)),
                ('daily_calories_consumed', models.PositiveIntegerField(default=0)),
                ('daily_protein_consumed', models.PositiveIntegerField(default=0)),
                ('daily_carbs_consumed', models.PositiveIntegerField(default=0)),
                ('daily_fat_consumed', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='health.user')),
            ],
            options={
                'db_table': 'progress',
                'ordering': ['-date'],
            },
        ),
    ]
