# Generated by Cursor on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0004_user_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lose_weight", "Lose weight"),
                    ("gain_muscle", "Gain muscle"),
                    ("maintain_weight", "Maintain weight"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]

