# Generated by Cursor on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0005_user_onboarding_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]

