# Generated by Cursor on 2026-04-27

from django.db import migrations


def seed_basic_foods(apps, schema_editor):
    Food = apps.get_model("health", "Food")

    seeds = [
        {
            "name": "Chicken breast, cooked",
            "brand": None,
            "calories_per_100g": 165,
            "protein_per_100g": 31,
            "carbs_per_100g": 0,
            "fat_per_100g": 3.6,
            "fiber_per_100g": 0,
            "sugar_per_100g": 0,
        },
        {
            "name": "Strawberries, raw",
            "brand": None,
            "calories_per_100g": 32,
            "protein_per_100g": 0.7,
            "carbs_per_100g": 7.7,
            "fat_per_100g": 0.3,
            "fiber_per_100g": 2.0,
            "sugar_per_100g": 4.9,
        },
        {
            "name": "White rice, cooked",
            "brand": None,
            "calories_per_100g": 130,
            "protein_per_100g": 2.7,
            "carbs_per_100g": 28.2,
            "fat_per_100g": 0.3,
            "fiber_per_100g": 0.4,
            "sugar_per_100g": 0.1,
        },
        {
            "name": "Broccoli, raw",
            "brand": None,
            "calories_per_100g": 34,
            "protein_per_100g": 2.8,
            "carbs_per_100g": 6.6,
            "fat_per_100g": 0.4,
            "fiber_per_100g": 2.6,
            "sugar_per_100g": 1.7,
        },
        {
            "name": "Whole egg, raw",
            "brand": None,
            "calories_per_100g": 143,
            "protein_per_100g": 13,
            "carbs_per_100g": 0.7,
            "fat_per_100g": 10,
            "fiber_per_100g": 0,
            "sugar_per_100g": 0.4,
        },
        {
            "name": "Greek yogurt, plain nonfat",
            "brand": None,
            "calories_per_100g": 59,
            "protein_per_100g": 10.3,
            "carbs_per_100g": 3.6,
            "fat_per_100g": 0.4,
            "fiber_per_100g": 0,
            "sugar_per_100g": 3.2,
        },
        {
            "name": "Banana, raw",
            "brand": None,
            "calories_per_100g": 89,
            "protein_per_100g": 1.1,
            "carbs_per_100g": 22.8,
            "fat_per_100g": 0.3,
            "fiber_per_100g": 2.6,
            "sugar_per_100g": 12.2,
        },
        {
            "name": "Olive oil",
            "brand": None,
            "calories_per_100g": 884,
            "protein_per_100g": 0,
            "carbs_per_100g": 0,
            "fat_per_100g": 100,
            "fiber_per_100g": 0,
            "sugar_per_100g": 0,
        },
    ]

    for data in seeds:
        Food.objects.get_or_create(
            name=data["name"],
            defaults=data,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0006_alter_user_email_unique"),
    ]

    operations = [
        migrations.RunPython(seed_basic_foods, migrations.RunPython.noop),
    ]

