# Generated by Django 6.0.1 on 2026-04-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_seed_basic_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text='Used for calorie estimates', max_length=1, null=True),
        ),
    ]
